spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fntxdata?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 2008Xiatian
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
  devtools:
    add-properties: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: jtravel-nacos
        heart-beat-timeout: 5000
knife4j:
  enable: true
  markdowns: classpath:markdown/*
debug: true